shop/urls.py
from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^$', views.index,
        name='shop.index'),

    url(r'^list-categories/(?P<server_slug>[\w-]+)/$', views.list_categories,
        name='shop.list-categories'),

    url(r'^buy-item/(?P<slug>[\w-]+)/$', views.buy_item,
        name='shop.buy-item'),
    url(r'^validate-username/(?P<server_slug>[\w-]+)/(?P<minecraft_username>[\w-]+)/$',
        views.validate_username, name='shop.validate-username'),
    url(r'^valid-buy-item/$', views.valid_buy_item,
        name='shop.valid-buy-item'),
    url(r'^confirm-buy-item/$', views.confirm_buy_item,
        name='shop.confirm-buy-item'),

    url(r'^buy-credits/$', views.buy_credits,
        name='shop.buy-credits'),
    url(r'^buy-credits-paypal/$', views.buy_credits_paypal,
        name='shop.buy-credits-paypal'),
    url(r'^buy-credits-dedipass/$', views.buy_credits_dedipass,
        name='shop.buy-credits-dedipass'),
    url(r'^buy-credits-paysafecard/$', views.buy_credits_paysafecard,
        name='shop.buy-credits-paysafecard'),

    url(r'^validate-credits-paypal/$', views.validate_credits_paypal,
        name='shop.validate-credits-paypal'),
    url(r'^validate-credits-dedipass/$', views.validate_credits_dedipass,
        name='shop.validate-credits-dedipass'),
    url(r'^validate-credits-paysafecard/$', views.validate_credits_paysafecard,
        name='shop.validate-credits-paysafecard'),

    url(r'^confirm-credits-paypal/$', views.confirm_credits_paypal,
        name='shop.confirm-credits-paypal'),
    url(r'^confirm-credits-dedipass/$', views.confirm_credits_dedipass,
        name='shop.confirm-credits-dedipass'),
    url(r'^confirm-credits-paysafecard/$', views.confirm_credits_paysafecard,
        name='shop.confirm-credits-paysafecard'),

    url(r'^cancel-credits-paypal/$', views.cancel_credits_paypal,
        name='shop.cancel-credits-paypal'),
]

website/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('pages.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^member/',  include('member.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'pages.views.handler404'
handler500 = 'pages.views.handler500'

website/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Config(models.Model):
    """
    Configuration du site.
    """
    global_promotion = models.DecimalField(_('Promotion globale'),
                                           max_digits=6, decimal_places=2)

    def __str__(self):
        return _('Configuration').format()

    class Meta:
        verbose_name = _('Configuration')
        verbose_name_plural = _('Configurations')


class Youtuber(models.Model):
    """
    Un « YouTubeur » est un vidéaste qui publie des vidéos sur YouTube
    concernant notre serveur.
    """
    username = models.CharField(_('Nom d\'utilisateur'), max_length=50,
                                unique=True)
    uuid = models.CharField(_('UUID'), max_length=36, unique=True, blank=True)
    url_youtube = models.CharField(_('URL YouTube'), max_length=255,
                                   blank=True)

    def __str__(self):
        return _('Youtubeur « {username} »').format(username=self.username)

    class Meta:
        verbose_name = _('Youtubeur')
        verbose_name_plural = _('Youtubeurs')


class StaffGroup(models.Model):
    name = models.CharField(_('Nom'), max_length=64)
    position = models.IntegerField(_('Position'), default=0)

    def __str__(self):
        return _('Groupe d\'équipe « {name} »').format(name=self.name)

    class Meta:
        verbose_name = _('Groupe')
        verbose_name_plural = _('Groupes')
        ordering = ('position',)


class StaffMember(models.Model):
    name = models.CharField(_('Nom'), max_length=50, blank=True)
    username = models.CharField(_('Nom d\'utilisateur'), max_length=50,
                                blank=True)
    uuid = models.CharField(_('UUID'), max_length=36, blank=True)
    short_description = models.CharField(_('Description courte'),
                                         max_length=128, blank=True)
    group = models.ForeignKey(StaffGroup, on_delete=models.CASCADE,
                              verbose_name=_('Groupe'))
    position = models.IntegerField(_('Position'), default=0)

    def __str__(self):
        return _('Membre d\'équipe « {username} »').format(
            username=self.username)

    class Meta:
        verbose_name = _('Membre')
        verbose_name_plural = _('Membres')
        ordering = ('position',)


class Page(models.Model):
    name = models.CharField(_('Nom'), max_length=128, blank=True)
    content = models.TextField(_('Contenu'), blank=True)
    slug = models.SlugField(_('Slug'), max_length=128, unique=True)

    def __str__(self):
        return _('Page « {name} »').format(name=self.name)

    class Meta:
        verbose_name = _('Page')
        verbose_name_plural = _('Pages')


class Recruitment(models.Model):
    name = models.CharField(_('Nom'), max_length=128)
    description = models.TextField(_('Description'), blank=True)
    image = models.ImageField(_('Image'), upload_to='./', blank=True)
    opened = models.BooleanField(_('Ouvert'), default=True)
    slug = models.SlugField(_('Slug'), max_length=128, unique=True)
    position = models.IntegerField(_('Position'), default=0)
    qualifications = models.TextField(_('Qualifications'), blank=True)

    def __str__(self):
        return _('Recrutement « {name} »').format(name=self.name)

    class Meta:
        verbose_name = _('Recrutement')
        verbose_name_plural = _('Recrutements')


class RecruitmentRequest(models.Model):
    STATUSES = (
        ('TO_STUDY', _('À étudier')),
        ('ACCEPTED', _('Acceptée')),
        ('REFUSED', _('Refusée'))
    )

    email = models.EmailField(_('Adresse électronique'))
    message = models.TextField(_('Message'), blank=True)
    file = models.ImageField(_('Fichier'), upload_to='./', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name=_('Utilisateur'))
    recruitment = models.ForeignKey(Recruitment, on_delete=models.CASCADE,
                                    verbose_name=_('Recrutement'))
    status = models.CharField(_('Statut'), max_length=8, choices=STATUSES,
                              default='TO_STUDY')
    created_at = models.DateTimeField(_('Créé le'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Mis à jour le'), auto_now=True)

    def __str__(self):
        return _('Demande de recrutement « {recruitment_name} »').format(
            recruitment_name=self.recruitment.name)

    class Meta:
        verbose_name = _('Demande de recrutement')
        verbose_name_plural = _('Demandes de recrutement')


class Contact(models.Model):
    email = models.EmailField(_('Adresse électronique'))
    subject = models.CharField(_('Sujet'), max_length=255)
    minecraft_username = models.CharField(_('Pseudonyme Minecraft'),
                                          max_length=150)
    message = models.TextField(_('Message'))
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name=_('Utilisateur'))
    created_at = models.DateTimeField(_('Créé le'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Mis à jour le'), auto_now=True)

    def __str__(self):
        return _('Contact « {subject} »').format(subject=self.subject)

    class Meta:
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

pages/templates/pages/about.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <p>
        {% blocktrans trimmed with site_name=site_name %}
            Neque accumsan iaculis aptenté massè dolor bibéndum ipsum
            ullamcorper éléfantid eu vélit ut purus dïam malésdum libéro, dolor
            fancibüs aptent elit dictumst augue séd sociosqu liçlà at consequat
            suspendisse tempès du pésuéré quîs, anté nisl gravida volutpat
            ultrices ultrices nulla est maécènas énis juséo felis cursus
            tristiqué vehiculâ. Tincidunt donéc feugiat pharetra nequé fancibüs
            pésuéré ïd léo d'anonyma quîs sodales arcû, quisque vivérra
            imperdiét quîs accumsan lacîna velit congue litoré variûs anonyma
            anté, aenean ad tellus quîs senectus j'pellentesque duis odio
            dapibus tortor eleifend.
        {% endblocktrans %}
    </p>
{% endblock %}

pages/templates/pages/confirm-contact.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}
    <p>
        {% blocktrans trimmed %}
            Votre message a bien été reçu.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans trimmed %}
            Nous vous répondrons d'ici peu.
        {% endblocktrans %}
    </p>
{% endblock %}

pages/templates/pages/confirm-recruitment.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}
    <p>
        {% blocktrans trimmed %}
            Votre demande de recrutement a bien été reçue.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans trimmed %}
            Nous vous répondrons d'ici peu.
        {% endblocktrans %}
    </p>
{% endblock %}

pages/templates/pages/contact.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{ contact_form.as_p }}

        <div class="text-right mt3">
            <button type="submit" class="btn btn-primary btn-block btn-large">{% trans 'Envoyer' %}</button>
        </div>
    </form>
{% endblock %}

pages/templates/pages/fight.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <h1 class="text-center">
        {% blocktrans trimmed with winner_username=fight.get_winner_username loser_username=fight.get_loser_username %}
            Combat entre {{ winner_username }} et {{ loser_username }}
        {% endblocktrans %}
    </h1>

    <p class="fight-dates">
        {% blocktrans trimmed with start_date=fight.get_started_date|date:'d F Y à G:i:s' %}
            <strong>Début du combat :</strong> {{ start_date }}
        {% endblocktrans %}

        &ndash;

        {% blocktrans trimmed with end_date=fight.get_ended_date|date:'d F Y à G:i:s' %}
            <strong>Fin du combat :</strong> {{ end_date }}
        {% endblocktrans %}
    </p>

    <ul class="fight-metadata">
        <li class="fight-metadata-item">
            {% blocktrans trimmed with kit_name=fight.get_kit_name %}
                <strong>Kit :</strong> {{ kit_name }}
            {% endblocktrans %}
        </li>

        <li class="fight-metadata-item">
            {% blocktrans trimmed with arena_name=fight.arena %}
                <strong>Arène :</strong> {{ arena_name }}
            {% endblocktrans %}
        </li>

        {% if fight.is_ranked %}
            <li class="fight-metadata-item">
                {% blocktrans trimmed %}
                    <strong>Classé</strong>
                {% endblocktrans %}
            </li>
        {% else %}
            <li class="fight-metadata-item">
                {% blocktrans trimmed %}
                    <strong>Non classé</strong>
                {% endblocktrans %}
            </li>
        {% endif %}
    </ul>

    <div class="fight">
        <div class="fight-winner">
            <div class="fight-status">
              {% trans 'Gagnant' %}
            </div>

            <div class="fight-avatar">
                <img src="https://crafatar.com/avatars/{{ fight.get_winner_uuid }}?size=140" alt="" />
            </div>

            <div class="fight-username">
                {{ fight.get_winner_username }}
            </div>

            <div class="fight-uuid">
                {{ fight.get_winner_uuid }}
            </div>

            {% if fight.is_ranked %}
                <ul class="fight-elo">
                    <li class="fight-elo-item">
                        <strong>{% trans 'ELO' %}</strong>
                    </li>

                    <li class="fight-elo-item fight-elo-item-migration">
                        {{ fight.winners_old_elos }}
                        {% trans '➔' %}
                        {{ fight.winners_new_elos }}
                    </li>

                    <li class="fight-elo-item">
                        <strong>
                            {% if fight.get_winner_diff_elos > 0 %}
                                (+{{ fight.get_winner_diff_elos }})
                            {% elif fight.get_winner_diff_elos < 0 %}
                                ({{ fight.get_winner_diff_elos }})
                            {% else %}
                                ({% trans '0' %})
                            {% endif %}
                        </strong>
                    </li>
                </ul>
            {% endif %}
        </div>

        <div class="fight-vs">
            {% trans 'VS' %}
        </div>

        <div class="fight-loser">
            <div class="fight-status">
              {% trans 'Perdant' %}
            </div>

            <div class="fight-avatar">
                <img src="https://crafatar.com/avatars/{{ fight.get_loser_uuid }}?size=140" alt="" />
            </div>

            <div class="fight-username">
                {{ fight.get_loser_username }}
            </div>

            <div class="fight-uuid">
                {{ fight.get_loser_uuid }}
            </div>

            {% if fight.is_ranked %}
                <ul class="fight-elo">
                    <li class="fight-elo-item">
                        <strong>{% trans 'ELO' %}</strong>
                    </li>

                    <li class="fight-elo-item fight-elo-item-migration">
                        {{ fight.losers_old_elos }}
                        {% trans '➔' %}
                        {{ fight.losers_new_elos }}
                    </li>

                    <li class="fight-elo-item">
                        <strong>
                            {% if fight.get_loser_diff_elos > 0 %}
                                (+{{ fight.get_loser_diff_elos }})
                            {% elif fight.get_loser_diff_elos < 0 %}
                                ({{ fight.get_loser_diff_elos }})
                            {% else %}
                                ({% trans '0' %})
                            {% endif %}
                        </strong>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

pages/templates/pages/index.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}
    <header class="header-home">
        <div class="header-title">
            <h1>
                {% blocktrans trimmed %}
                    {{ site_name }}
                {% endblocktrans %}
            </h1>

            <p class="header-subtitle">
                {% blocktrans trimmed %}
                    Serveur Minecraft Network
                {% endblocktrans %}
            </p>

            <img src="{% static 'img/logo.png' %}"
                 alt="{% blocktrans trimmed %}Logo {{ site_name }}{% endblocktrans %}" />
        </div>

        <div class="header-join">
            <p class="txt-join">
                {% blocktrans trimmed %}
                    Nous rejoindre
                {% endblocktrans %}
            </p>

            <div>
                <p class="txt-ip">
                    {% blocktrans trimmed %}
                        {{ minecraft_ip }}
                    {% endblocktrans %}
                </p>
            </div>

            <p class="txt-versions">
                {% blocktrans trimmed %}
                    Versions 1.7 à 1.13 – Connectés : {{ nb_players }}
                {% endblocktrans %}
            </p>
        </div>
    </header>

    <section class="section-presentation">
        <div class="wrapper">
            <div class="col-6 col-image">
                <img src="{% static 'img/black-placeholder.jpg' %}">
            </div>

            <div class="col-6 col-text">
                <h2>
                    {% blocktrans trimmed %}
                        Aenean aliquam suspendisse
                    {% endblocktrans %}
                </h2>

                {% blocktrans trimmed %}
                    Commodoe sit luctus hâc nisi conséquat mattisé rûtrum laçus
                    suscipit mlius pretium sociosqu, à rhoncüs alèquam intègèr
                    sét himenaeos conséquat conséquat blandît cursus ad aenean,
                    ultricies taciti félis j'condimentûm anonyma primis
                    phasellus ut quisqué.
                {% endblocktrans %}
            </div>
        </div>
    </section>

    <section class="section-presentation section-dark">
        <div class="wrapper">
            <div class="col-6 col-text">
                <h2>
                    {% blocktrans trimmed %}
                        Congue tempès variûs
                    {% endblocktrans %}
                </h2>

                {% blocktrans trimmed %}
                    Molestie torquenté fuegiuia himenaeos convallis venenatis
                    pharétra tristiqué séllicitudén énis ad prétium, nisl mi
                    malesuada nisï lectus convallis pellentesque dolor
                    portitorsé litoré arcu tristiqué.
                {% endblocktrans %}
            </div>

            <div class="col-6 col-image">
                <img src="{% static 'img/white-placeholder.jpg' %}">
            </div>
        </div>
    </section>

    <section class="section-presentation">
        <div class="wrapper">
            <div class="col-6 col-image">
                <img src="{% static 'img/black-placeholder.jpg' %}">
            </div>

            <div class="col-6 col-text">
                <h2>
                    {% blocktrans trimmed %}
                        Neque accumsan iaculis aptenté massè dolor
                    {% endblocktrans %}
                </h2>

                {% blocktrans trimmed %}
                    Lorem torétoré scelerisque curae lilitoxic anonyma cél
                    l'fermentum pulvîar ut torquent, suspendissé nec mi c'est
                    fermentum risius nullä classé donec, elit primis congue mi
                    rhoncüs cél velit class non netus diam famès. Urna
                    ullamcorper curae justo étiam ultricies laoreet ultrûcéas
                    l'vivamus, orci aliquet ornare tempor nètus néc aptenté,
                    torquenté rûtrum sagittis classé accumsan scéléréo.
                {% endblocktrans %}
            </div>
        </div>
    </section>
{% endblock %}

pages/templates/pages/legal-notice.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    {% comment %}
        Placer ici les mentions légales du site.

        @see https://www.service-public.fr/professionnels-entreprises/vosdroits/F31228
    {% endcomment %}

    <p>
        {% blocktrans trimmed with site_name=site_name %}
            Lorem torétoré scelerisque curae lilitoxic anonyma cél l'fermentum
            pulvîar ut torquent, suspendissé nec mi c'est fermentum risius
            nullä classé donec, elit primis congue mi rhoncüs cél velit class
            non netus diam famès. Urna ullamcorper curae justo étiam ultricies
            laoreet ultrûcéas l'vivamus, orci aliquet ornare tempor nètus néc
            aptenté, torquenté rûtrum sagittis classé accumsan scéléréo.
        {% endblocktrans %}
    </p>
{% endblock %}

pages/templates/pages/page.html
{% extends 'base.html' %}

{% block content %}
    {{ page.content|safe }}
{% endblock %}

pages/templates/pages/ranking.html
{% extends 'base.html' %}

{% block content %}
    <div class="leaderboard">
        {% include 'pages/stats-table.html' with title='Global' stats=global_elo only %}
    </div>

    <h2 class="text-center">Classement</h2>

    <div class="leaderboard">
        {% include 'pages/stats-table.html' with title='NoDebuff' stats=elo_nodebuffelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Build UHC' stats=elo_builduhcelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Archer' stats=elo_archerelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Gapple' stats=elo_gappleelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Combo' stats=elo_comboelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Combo Sumo' stats=elo_combosumoelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Sumo' stats=elo_sumoelo1v1 only %}
        {% include 'pages/stats-table.html' with title='Spleef' stats=elo_spleefelo1v1 only %}
    </div>

    <h2 class="text-center">Classement Premium</h2>

    <div class="leaderboard">
        {% include 'pages/stats-table.html' with title='NoDebuff Premium' stats=elo_nodebuffelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Build UHC Premium' stats=elo_builduhcelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Archer Premium' stats=elo_archerelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Gapple Premium' stats=elo_gappleelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Combo Premium' stats=elo_comboelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Combo Sumo Premium' stats=elo_combosumoelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Sumo Premium' stats=elo_sumoelo1v1premium only %}
        {% include 'pages/stats-table.html' with title='Spleef Premium' stats=elo_spleefelo1v1premium only %}
    </div>
{% endblock %}

pages/templates/pages/recruitments.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <div class="recruitment-cards">
        {% for recruitment in recruitments %}
            {% if recruitment.opened %}
                <a class="recruitment-card" href="{% url 'recruitment' recruitment.slug %}">
            {% else %}
                <div class="recruitment-card">
            {% endif %}
                {% if recruitment.image %}
                    <div class="recruitment-card-image">
                        <img src="{{ recruitment.image.url }}" alt="" />
                    </div>
                {% endif %}

                <div class="recruitment-card-header">
                    {{ recruitment.name }}
                </div>

                {% if recruitment.description %}
                    <div class="recruitment-card-description">
                        {{ recruitment.description|safe }}
                    </div>
                {% endif %}

                <div class="recruitment-opening-state">
                    {% if recruitment.opened %}
                        <span class="recruitment-opening-state-opened">
                            {% trans 'Ouvert' %}
                        </span>
                    {% else %}
                    <span class="recruitment-opening-state-closed">
                            {% trans 'Fermé' %}
                        </span>
                    {% endif %}
                </div>
            {% if recruitment.opened %}
                </a>
            {% else %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

pages/templates/pages/staff.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    {% for group in groups %}
        <div>
            <h2 class="text-center">
                {{ group.name }}
            </h2>

            <div class="member-cards">
                {% for member in group.staffmember_set.all %}
                    <div class="member-card">
                        <div class="member-card-header">
                            <img src="https://crafatar.com/avatars/{{ member.uuid }}?size=60&amp;helm"
                                 class="member-card-image"
                                 alt="" />

                            <div class="member-card-names">
                                {% if member.name %}
                                    <p class="member-card-name">
                                        <strong>Nom</strong><br />
                                        {{ member.name }}
                                    </p>
                                {% endif %}

                                {% if member.username %}
                                    <p class="member-card-username">
                                        {% blocktrans trimmed with username=member.username %}
                                            <strong>Pseudonyme</strong><br />
                                            {{ username }}
                                        {% endblocktrans %}
                                    </p>
                                {% endif %}
                            </div>
                        </div>

                        {% if member.short_description %}
                            <p class="member-card-description">
                                {{ member.short_description }}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

pages/templates/pages/stats-table.html
{% load i18n %}

<div class="leaderboard-item">
    <table class="leaderboard-table">
        <tr>
            <th colspan="3">
                {{ title }}
            </th>
        </tr>

        <tr>
            <th></th>

            <th>
                {% trans 'Pseudonyme' %}
            </th>

            <th class="text-right">
                {% trans 'Elo' %}
            </th>
        </tr>

        {% for stat in stats %}
            <tr>
                <td class="text-right">
                    #{{ forloop.counter }}
                </td>

                <td>
                  <img src="https://crafatar.com/avatars/{{ stat.uuid }}?size=16"
                         alt="" />

                    {{ stat.username }}
                </td>

                <td class="text-right">
                    {{ stat.score }}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

pages/templates/pages/summary.html
{% extends 'base.html' %}

{% load i18n flux_name %}

{% block content %}
    <table>
        <tr>
            <td>{% trans 'PayPal' %}</td>
            <td>+{{ gain_paypal }}</td>
        </tr>

        <tr>
            <td>{% trans 'Dedipass' %}</td>
            <td>+{{ gain_dedipass }}</td>
        </tr>

        <tr>
            <td>{% trans 'paysafecard' %}</td>
            <td>+{{ gain_paysafecard }}</td>
        </tr>

        <tr>
            <td>{% trans 'Entrée' %}</td>
            <td>+{{ income }}</td>
        </tr>

        <tr>
            <td>{% trans 'Sortie' %}</td>
            <td>-{{ output }}</td>
        </tr>

        <tr>
            <td><strong>{% trans 'Total' %}</strong></td>
            <td>
                {% if total >= 0 %}
                    <strong style="color: green;">{{ total }}</strong>
                {% else %}
                    <strong style="color: red;">{{ total }}</strong>
                {% endif %}
            </td>
        </tr>
    </table>

    <table class="summary-table">
        <tr>
            <th>
                Mois
            </th>

            {% for heading in headings %}
                <th>
                    {{ heading|flux_name }}
                </th>
            {% endfor %}
        </tr>

        {% for month, flux in fluxes.items %}
            <tr>
                <td>
                    {{ month|date:'F Y' }}
                </td>

                {% for id, amount in flux.items %}
                    <td>
                        {{ amount }} €
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

pages/templates/pages/youtubers.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <div class="cards">
        {% for youtuber in youtubers %}
            {% if youtuber.url_youtube %}
                <a class="card" href="{{ youtuber.url_youtube }}">
                    <img src="https://crafatar.com/avatars/{{ youtuber.uuid }}?size=60&amp;helm"
                         alt="" />

                    <span style="vertical-align: 70%; font-size: 1.3em; padding-left: 8px;">
                        {{ youtuber.username }}
                    </span>
                </a>
            {% else %}
                <div class="card">
                    <img src="https://crafatar.com/avatars/{{ youtuber.uuid }}?size=60&amp;helm"
                         alt="" />

                    <span style="vertical-align: 70%; font-size: 1.3em; padding-left: 8px;">
                        {{ youtuber.username }}
                    </span>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}